Rebase README

diff --git a/restic-repos b/restic-repos
--- a/restic-repos
+++ b/restic-repos
@@ -1,24 +1,43 @@
 #!/bin/bash
 
 export RESTIC_REPOS_DIR=/usr/local/etc
+export REPO_DIRNAME=restic-repos.d
 
-if [[ "$(whoami)" != "root" ]]; then echo "This command must be run as root." 1>&2; exit 0; fi
+function helpdoc {
+    echo ""
+    cat "$RESTIC_REPOS_DIR/$REPO_DIRNAME/help.txt"
+    echo ""
+}
 
-if [[ "$1" == "lsrepo" ]]; then echo "$(ls $RESTIC_REPOS_DIR/restic-repos -1I README*)"; exit 0; fi
+function repolist {
+    list="$(ls -1d $RESTIC_REPOS_DIR/$REPO_DIRNAME/*/)"
+    for dir in $list; do baselist+="$(basename $dir)\n"; done
+    echo -e $baselist | sed -z '$ s/\n$//'
+}
+
+if [[ "$(whoami)" != "root" ]]; then echo "this command must be run as root." 1>&2; exit 0; fi
+
+if [[ "$1" == "lsrepo"  ]] || [[ "$1" == "-l" ]]; then 
+    repolist
+    exit 0
+elif [[ "$1" == "help" ]] || [[ "$1" == "-h" ]]; then
+    helpdoc
+    exit 0
+fi
 
 set -e
 
-repodir=$RESTIC_REPOS_DIR/restic-repos/$1
+repodir=$RESTIC_REPOS_DIR/$REPO_DIRNAME/$1
 
 if [[ "$2" == "init" && ! -d "$repodir" ]]; then
     mkdir -p "$repodir"
-    cp -r "$RESTIC_REPOS_DIR/restic-repos/.default/." "$repodir/."
+    cp -r "$RESTIC_REPOS_DIR/$REPO_DIRNAME/.default/." "$repodir/."
     chmod 700 "$repodir/env"
     ${EDITOR:-${VISUAL:-vi}} "$repodir/env"
 fi
 
-if [[ ! -d "$repodir" ]]; then echo "Invalid repository given." 1>&2; exit 0; fi
-if [[ "$#" -lt 2 ]]; then printf "Usage: restic-repos REPO [restic args] or restic-repos lsrepo\nSee README for more help." 1>&2; exit 0; fi
+if [[ ! -d "$repodir" ]]; then echo "repo $1 not found." 1>&2; helpdoc; exit 0; fi
+if [[ "$#" -lt 2 ]]; then echo "repo $1 found but no restic commands were given..." 1>&2; helpdoc; exit 0; fi
 
 source "$repodir/env"
 if [[ -z "$RESTIC_PASSWORD_FILE" ]]; then 
@@ -31,7 +50,6 @@ fi
 
 if [[ "$2" == "autobackup" ]]; then
     if [[ -n $(pgrep "restic" | grep "restic backup") ]]; then echo "restic backup is already running..." 1>&2; exit 0; fi
-    
     restic unlock
     restic backup --files-from-verbatim "$repodir/includes.conf" --exclude-file="$repodir/excludes.conf" --tag "autobackup"
     restic check --with-cache --read-data-subset=5G
@@ -41,5 +59,13 @@ elif [[ "$2" == "edit" ]]; then
     elif [[ -w "$repodir/$3.conf" ]]; then ${EDITOR:-${VISUAL:-vi}} "$repodir/$3.conf"
     else echo "Not a valid config..." 1>&2; exit 0; fi;
 else
-    exec restic "${@:2}"
+    if [[ "$2" == "backup" ]]; then 
+        exec restic "${@:2}" --files-from-verbatim "$repodir/includes.conf" --exclude-file="$repodir/excludes.conf"
+    elif [[ "$2" == "restore" ]]; then
+        exec restic "${@:2}" --include-file="$repodir/includes.conf" --exclude-file="$repodir/excludes.conf"
+    elif [[ "$2" == "rewrite" ]]; then
+        exec restic "${@:2}" --exclude-file="$repodir/excludes.conf"
+    else 
+        exec restic "${@:2}"
+    fi
 fi
